### ISSUE TITLE
New version 2.1.4 or greater performance is low.

### ISSUE THREAD

**Issue by lefay1982** [mrniko/redisson#338] opened 2015-12-17 13:23 UTC
When I use redisson 2.1.3 the ubuntu's load average is 1.8 ~ 2.3; but I use 2.1.4 or greater, the load average is often greater than 3.00, my java application often overload.

**Comment by mrniko** [comment] 2015-12-17 13:25
Which Redisson objects do you use in your application?

**Comment by mrniko** [comment] 2015-12-17 13:27
Also try the latest Redisson version - 2.2.3. Because Redisson has lot of changes since 2.1.4 version.

**Comment by lefay1982** [comment] 2015-12-18 07:54
I have test  2.1.4    2.1.6   2.2.0      2.2.3         cpu and memory also increase more than 2.1.3.

**Comment by mrniko** [comment] 2015-12-18 08:03
Ok, will check it too

**Comment by mrniko** [comment] 2015-12-18 08:04
@lefay1982 also try to change netty version. Redisson uses netty 4.0.32 since 2.1.4 version. 2.1.3 uses 4.0.30. Maybe this affects performance

**Comment by lefay1982** [comment] 2015-12-18 08:20
Run 17 hours, the new version after 2.1.3  res increase 1.019g and 800M.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                   
 1020 root      20   0 3563004 1.019g   6436 S   7.9 26.4 381:40.31 java                                                                                                                      
 1019 root      20   0 3609728 274328   4552 S   5.7  6.8  81:15.25 java                                                                                                                      
 1022 root      20   0 3553692 866980   6040 S   4.5 21.4 406:50.26 java                                                                                                                      
 1029 root      20   0 3563380 898648   6188 S   3.4 22.2 452:04.97 java     

the other machine the  res is 300M and 500M
26459 root      20   0 3737492 369828   7716 S  63.0  9.1 536:16.80 java                                                                                                                      
26418 root      20   0 3705568 380572   7864 S  37.5  9.4 488:18.65 java                                                                                                                      
26434 root      20   0 3693408 382884   7896 S  36.2  9.5 540:06.79 java                                                                                                                      
26416 root      20   0 3674520 505140   7608 S   6.0 12.5 108:08.33 java

**Comment by mrniko** [comment] 2015-12-18 08:24
Let's move to gitter chat to discuss :)

**Comment by mrniko** [comment] 2015-12-18 08:42
I ran load-tests with one Redisson client, 25 threads each of them executed task with two Redisson operations: RDeque.addLast(randomString) and RDeque.getFirst(). Total tasks amount is 1.000.000

Here is my results:
For Redisson 2.1.3
![redisson_2 1 3](https://cloud.githubusercontent.com/assets/1104661/11892671/76c1add0-a57b-11e5-8fac-b2bce4c9818d.png)

For Redisson 2.2.3
![redisson_2 2 3](https://cloud.githubusercontent.com/assets/1104661/11892777/4134f9b4-a57c-11e5-9f05-ec0883e53651.png)

I don't see much difference in CPU consumption. As for memory, with 2.2.3 version memory footprint looks better.

**Comment by mrniko** [comment] 2015-12-20 08:17
@lefay1982 Does it work well now?

**Comment by lefay1982** [comment] 2015-12-20 11:44
no, after deploy 1 machine the 2.2.4-SNAPSHOT,  all my apps is run abnormal.

**Comment by mrniko** [comment] 2015-12-21 08:03
ok, I'll continue investigation

**Comment by mrniko** [comment] 2015-12-21 12:42
@lefay1982 i have reduced memory allocation by listeners. Please check last build

**Comment by lefay1982** [comment] 2015-12-25 04:38
my gitter is not use,  I check the latest code, and run,  all my server is not load, redis no output bytes.
I set the  master pool size and slave pool size is 50,  if the connection is not the cause, maybe have a method consumed many connection. so the connection pool is empty.

**Comment by lefay1982** [comment] 2015-12-25 04:48
I only use   RMap RAtomicLong RSet   RLock  RQueue,  RBucket.

**Comment by mrniko** [comment] 2015-12-25 08:58
I tried this config and it works.

```java
    config.useSentinelServers().setMasterName("mymaster").addSentinelAddress("127.0.0.1:26379", "127.0.0.1:26389")
    .setSlaveConnectionPoolSize(50)
    .setMasterConnectionPoolSize(50);
```

**Comment by lefay1982** [comment] 2015-12-25 09:00
Now I used is config.userMasterSlaveServers();

**Comment by lefay1982** [comment] 2015-12-25 09:02
Run test is OK
But deploy to work server. is down , but  v2.1.3 is OK. I returned to 2.1.3.

**Comment by mrniko** [comment] 2015-12-25 09:02
> But deploy to work server. is down

Sorry, what does it mean?

**Comment by mrniko** [comment] 2015-12-25 09:04
Could you describe steps to reproduce it?

**Comment by mrniko** [comment] 2015-12-25 09:09
I tried follow scenarios with useMasterSlaveServers (1 master, 2 slaves):

1. stop 1 slave, then start it again. Client continues to work
2. stop two slaves, then start them again. Client continues to work
3. stop master, then start it again. Client continues to work

All tests are passed for me.

**Comment by lefay1982** [comment] 2015-12-25 09:59
"epollEventLoopGroup-4-2" prio=10 tid=0x00007f03e0004000 nid=0x6153 in Object.wait() [0x00007f0450e32000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:461)
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:355)
	- locked <0x00000007843f5d58> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:306)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:293)


"epollEventLoopGroup-4-1" prio=10 tid=0x00007f03e0007800 nid=0x6152 in Object.wait() [0x00007f0450f33000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
	- locked <0x00000007dc3f8dc0> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:32)
	at org.redisson.CommandExecutorService.get(CommandExecutorService.java:181)
	at org.redisson.CommandExecutorService.read(CommandExecutorService.java:196)
	at org.redisson.RedissonMap.containsKey(RedissonMap.java:88)

"epollEventLoopGroup-4-5" prio=10 tid=0x00007f03e000a000 nid=0x616c in Object.wait() [0x00007f0450832000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
	- locked <0x00000007db8cde78> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:32)
	at org.redisson.CommandExecutorService.get(CommandExecutorService.java:181)
	at org.redisson.RedissonObject.get(RedissonObject.java:48)
	at org.redisson.RedissonMap.put(RedissonMap.java:142)

"nioEventLoopGroup-6-8" prio=10 tid=0x00007f040c074800 nid=0x61e6 runnable [0x00007f03ce1eb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x00000007834ff838> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000007834ff898> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007834ff7a0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lefay1982** [comment] 2015-12-25 10:01
when run some time in my server.  and stop nginx not let client  call server's,  my app's cpu is 40%.
Then I jstack the app , show me these infomations.

**Comment by mrniko** [comment] 2015-12-25 10:42
![untitled](https://cloud.githubusercontent.com/assets/1104661/12002351/f5a534e6-ab0c-11e5-9a84-9849f20bba28.png)
Here is my cpu graph. During graph pit servers are down, almost 0% during this time. Then servers are up CPU consumption backs to usual level.

**Comment by lefay1982** [comment] 2015-12-25 11:03
Netty's EventLoopGroup  bossGroup and workderGroup What Number you set?

**Comment by lefay1982** [comment] 2015-12-25 11:04
I think is my netty's setting have problem.

**Comment by mrniko** [comment] 2015-12-25 11:07
@lefay1982 I didn't touch any of those settings. My settings are:

```java
      config.useMasterSlaveServers().setMasterAddress("127.0.0.1:6399").addSlaveAddress("127.0.0.1:6379").addSlaveAddress("127.0.0.1:6389")
    .setSlaveConnectionPoolSize(50)
    .setMasterConnectionPoolSize(50);

```

**Comment by mrniko** [comment] 2015-12-25 12:20
Also, there is no `bossGroup` for `io.netty.bootstrap.Bootstrap.Bootstrap` client instance.

**Comment by lefay1982** [comment] 2015-12-25 12:22
OK, I user Netty for Server instance.

**Comment by lefay1982** [comment] 2015-12-28 16:43
hi @mrniko here has a exception of v2.2.4:

ERROR [com.sdk.biz.snowfox.adpush.AdPushServer$AdAction] error
org.redisson.client.RedisException: ERR Error running script (call to f_9401052d872adfd0179ef8c8e8c028512707629a): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0xe61fdefb, /10.117.238.103:43493 => /10.204.16.23:7001] command: CommandData [promise=DefaultPromise@aff3759(incomplete), command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);, 1, ad:lock:adOfferMap:423, 29000, d1dae71c-d3fa-43c6-ad50-49c14a4d2836:56], codec=org.redisson.client.codec.LongCodec@798ab9b2]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:184) ~[redisson-2.2.4.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:109) ~[redisson-2.2.4.jar:na]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376) ~[netty-all-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[netty-all-4.0.33.Final.jar:4.0.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-all-4.0.33.Final.jar:4.0.33.Final]

**Comment by lefay1982** [comment] 2015-12-28 16:44
when using RLock.

**Comment by lefay1982** [comment] 2015-12-28 17:23
2015-12-29 01:17:55.212 epollEventLoopGroup-4-1 ERROR [com.sdk.biz.snowfox.adpush.AdPushServer$AdAction] error
org.redisson.client.RedisException: ERR Error running script (call to f_9401052d872adfd0179ef8c8e8c028512707629a): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value . channel: [id: 0xe61fdefb, /10.117.238.103:43493 => /10.204.16.23:7001] command: CommandData [promise=DefaultPromise@6cd9f6cb(incomplete), command=(EVAL), params=[if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);, 1, ad: lock:adOfferMap:1219, 29000, d1dae71c-d3fa-43c6-ad50-49c14a4d2836:38], codec=org.redisson.client.codec.LongCodec@798ab9b2]

**Comment by mrniko** [comment] 2015-12-28 17:39
@lefay1982 you need to recreate lock it's not compatible with 2.1.3 version

**Comment by lefay1982** [comment] 2015-12-28 18:03
I start 7 instance, but  1 instace update 2.2.4. this is the cause.

**Comment by mrniko** [comment] 2015-12-28 18:33
So now you using 2.2.4 in all instances. Am I right?

**Comment by lefay1982** [comment] 2015-12-29 03:56
when I deploy 2.2.4 in all instances, RMap.fastPut can not put value to Redis, but fastRemove can remove, cause my Redis's data removed.

In 2.1.3 the RBatch.executeAsync not put my data to Redis.
but the  RBatch.execute can put the data to Redis,
please check.

**Comment by mrniko** [comment] 2015-12-29 06:13
I launched RMap tests and they all are passed. `RBatch.execute` based on `RBatch.executeAsync`. Therefore if `RBatch.executeAsync` doesn't work then `RBatch.execute` shouldn't too.

**Comment by mrniko** [comment] 2016-01-05 06:46
@lefay1982 any news?

**Comment by lefay1982** [comment] 2016-01-06 08:15
Have no time to test.

**Comment by mrniko** [comment] 2016-01-07 19:24
@lefay1982 major bug with `RBatch` was fixed in https://github.com/mrniko/redisson/issues/361

**Closed** 2016-01-09 05:31 UTC
Labels: bug
