### ISSUE TITLE
Redisson cluster Read connections issue

### ISSUE THREAD

**Issue by zhxjouc** [mrniko/redisson#345] opened 2015-12-24 10:38 UTC
I use Redisson 2.2 to implement distributed lock in my project and use Redis cluster.  And I found the Redisson client will create new connection and do not use the connection in the pool while invoke some readOnly methods which execute evalRead. So when I start to run the test it will produce lots of TIME_WAIT connection on my server. The followings are some logs on my server.
``
12/24/15 08:59:06:949: [SimpleProcessor-0]: DEBUG org.redisson.cluster.ClusterConnectionManager - slot 8978 for USER_WALLETS-test
``
``
12/24/15 08:59:06:949: [nioEventLoopGroup-2-2]: DEBUG org.redisson.command.CommandSyncService - getting connection for command (EVAL) from slot NodeSource [slot=8978, addr=null, redirect=null] using node /192.168.1.51:2500
``
``
12/24/15 08:59:06:950: [nioEventLoopGroup-2-6]: DEBUG org.redisson.connection.ClientConnectionsEntry - new connection created: RedisConnection [redisClient=RedisClient [addr=/168.168.1.54:2000], channel=[id: 0xc239f9bb, /192.168.1.11:43560 => /192.168.1.54:2000]]
``
``
12/24/15 08:59:06:951: [nioEventLoopGroup-2-4]: DEBUG org.redisson.command.CommandSyncService - getting connection for command (EVAL) from slot NodeSource [slot=8978, addr=/192.168.1.54:2000, redirect=MOVED] using node /168.168.1.54:2000
``
The codes are very spectacular and I only understand a bit. But I doubt whether the client get the connection from the pool but also create a new one?

**Comment by mrniko** [comment] 2015-12-24 11:12
Hi! There was a bug fixed in https://github.com/mrniko/redisson/commit/4c897806f6a84a5bc9347ff92c007ae517a03fa1 Could you try it with latest build from master branch?

**Comment by mrniko** [comment] 2015-12-30 13:16
Fixed in 2.2.4

**Comment by zhxjouc** [comment] 2016-01-04 03:39
Hi mrniko
I'm sorry that I found it was still not work for Redisson 2.2.4 or Redssion 2.2.5(current master branch). And I think if the bug: 4c89780 result in this issue, it might impact on the connection for both evalRead and evalWrite . But in my case, only the evalRead has the connection issues. Maybe there are some other issues.

**Comment by mrniko** [comment] 2016-01-04 07:23
@zhxjouc could you provide some testcase or way to reproduce it?

**Comment by zhxjouc** [comment] 2016-01-04 07:40
Here are the step I create the lock:
1. create redisson client use Redis cluster mode
```
 config.useClusterServers().addNodeAddress....setReadFromSlaves(false);
```  
2. lock the value with lease time 
```
redisson.getLock(value).lock(60000, TimeUnit.MILLISECONDS)
```
Assume: the value hit 192.168.1.54:2000(master) and 192.168.1.51:2001(slave)
3. get the lock holdCount
```
 redisson.getLock(value).getHoldCount();
```
NOTE: first it will execute read operation on 192.168.1.51:2001(slave) and then create a new connection on 192.168.1.54:2000(master).

**Comment by mrniko** [comment] 2016-01-04 07:44
But RLock uses `evalWrite` operation and not `evalRead`

**Comment by zhxjouc** [comment] 2016-01-04 07:45
RLock.getHoldCount might use the evalRead

**Comment by mrniko** [comment] 2016-01-04 07:47
it uses `HGET` command

**Comment by zhxjouc** [comment] 2016-01-04 07:51
In RedissionLock.java
```
Long res = commandExecutor.read(getName(), LongCodec.INSTANCE, RedisCommands.HGET, getName(), getLockName());
```
In CommandSyncService.java
```
Future<R> res = readAsync(key, codec, command, params);
```
```
async(true, source, codec, command, params, mainPromise, 0);
```
The readOnlyMode is true, so it executes connectionReadOp

**Comment by mrniko** [comment] 2016-01-04 07:51
Do you use `RLock` object only?

**Comment by zhxjouc** [comment] 2016-01-04 07:52
Yes just use RedissonLock

**Comment by zhxjouc** [comment] 2016-01-04 07:53
And if I use the single mode for Redission client, it works

**Comment by mrniko** [comment] 2016-01-04 07:54
i see MOVED redirection reponses from cluster in your log:
`DEBUG org.redisson.command.CommandSyncService - getting connection for command (EVAL) from slot NodeSource [slot=8978, addr=/192.168.1.54:2000, redirect=MOVED]`

**Comment by mrniko** [comment] 2016-01-04 07:55
maybe MOVED redirection handling causes the connection leak

**Comment by zhxjouc** [comment] 2016-01-04 08:00
How this exception occurred

**Comment by zhxjouc** [comment] 2016-01-04 08:03
The master entry in slaveLoadbalance is freezed and it doesn't have a connection. Maybe when i execute readOperation, it execute the operation on both mater and slave. And the freezed master does not have a connection pool and will open a new one?

**Comment by mrniko** [comment] 2016-01-04 08:05
connection releasing logging added

**Comment by zhxjouc** [comment] 2016-01-04 08:08
Should I sync the newest code and rerun my case again in log DEBUG mode?

**Comment by mrniko** [comment] 2016-01-04 08:10
Yes

**Comment by mrniko** [comment] 2016-01-04 08:18
@zhxjouc oh, sorry! I have just committed the code.

**Comment by mrniko** [comment] 2016-01-04 08:34
i think cause of bug is in `setReadFromSlaves(false);` settings. I made some fixes for it. Could you please sync code from master branch and try it again?

**Comment by mrniko** [comment] 2016-01-04 08:36
Also you can join to redisson chat to discuss it further https://gitter.im/mrniko/redisson

**Comment by zhxjouc** [comment] 2016-01-04 08:37
OK I will try again
Do you mean that the redirect node does not use the connection pool?

**Comment by mrniko** [comment] 2016-01-04 08:41
any Redisson operation uses connection pool it's the only one place there connections live. But connection can't be returned then master node is freezed like in your case.

**Comment by zhxjouc** [comment] 2016-01-04 08:47
It seems to work and I will try to run more cases. Thanks for your help.
But I'm still not very clear about this issue and what you change. I will continue to study your codes

**Comment by mrniko** [comment] 2016-01-04 08:57
Nice! 

About my code changes. If readFromSlaves is false in settings then Redisson shouldn't use slaves for read operations and this was the cause of your problem.

**Comment by zhxjouc** [comment] 2016-01-04 09:28
Though it uses the slaves for read operations and any Redisson operation use connection pool, how it open the new connection

**Comment by mrniko** [comment] 2016-01-04 09:40
i think slave connection was in incorrect state due to it hasn't been initialized with READONLY command.

**Closed** 2016-01-05 06:46 UTC
Labels: bug
