### ISSUE TITLE
Deadlock on lock() and not only.

### ISSUE THREAD

**Issue by alexs20** [mrniko/redisson#530] opened 2016-06-15 19:57 UTC
Hi,
I want to raise the issue with deadlocks again.
This bug is still exist and making big headache. As before, It present itself only on very heavy loaded tasks, but in this case I is happens only when client talks to the claster which is located remotely.
With a single-local or claster-local servers I was unable to reproduce it, but with remote server it happens with rate 1 / 20 (means from 20 runs of "heavy-load" JUnit test it happens only once)
I can see where thread is locked down, it always stuck in CommandAsyncService.get(Future), on l.await() line and never exits from it. As I understand something wrong with mainPromise object, it is staying in incomplete state... and nobody change it. I tried to understand the logics in CommandAsyncService.async(...) function, which is actually deals with connection, retry, redirections and at end should release (or fail) the mainPromise object, but it is nightmare. All these spagetty with promises and futures made the code difficult to read and impossible to analyse. For sure BUG is there, but I am near to give-up. Any thoughts?

**Comment by mrniko** [comment] 2016-06-15 23:18
Same test-case?

**Comment by alexs20** [comment] 2016-06-15 23:40
Exactly. Something wrong with communication part. Tomorrow I will try to reproduce it and will send you stacktrace of stuck thread. 
And yes, the same test, but I am running it for non-stop for long period and connection has small latency ... client and cluster are in two different network segments, Ping shows 12 msec delay...

**Comment by kajelas** [comment] 2016-06-16 02:04
@mrniko 
Please look at the bug I mentioned in #491. The thread dump is similar to @alexs20 mentioned:

"http-nio-8001-exec-567" #5935 daemon prio=5 os_prio=0 tid=0x00007f15f81ca000 nid=0x6b3e waiting on condition [0x00007f154468a000] java.lang.Thread.State: WAITING (parking) at sun.misc.Unsafe.park(Native Method) - parking to wait for <0x00000000bf468fc8> (a java.util.concurrent.CountDownLatch$Sync) 
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997) 
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304) 
**at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) 
at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:95)** 
at org.redisson.RedissonObject.get(RedissonObject.java:55) 
at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:113) 
at org.redisson.RedissonLock.lock(RedissonLock.java:92) ...

In my situation it is related to pub/sub because `CommandAsyncService.get()` happens in the process of getting the subscription ack. So if the bug is not completely fixed in 2.2.16, there must be potential problems in the pub/sub, maybe still related to that pub/sub listeners are sometimes removed improperly.

**Comment by alexs20** [comment] 2016-06-16 02:37
Very similar but in my case it is get (tryAcquireAsync(...)). in RLock and one time I was able to see how it stuck on get(tryAcquireAsync(permits)) in RSemaphore. Looks like the communication part has a flaw where sometimes it looses response from the server and messes up with promise states(main, attempt, write, connection... )  The problem that they are hardly inter connected with listeners and multiple if-els state checking that make it almost impossible to narrow the problem down. I spend two days trying to catch this BUG, at home and at work, but unsuccessful. But what I do found that It is probably, somehowe, connected with timeout timer. By slowly reducing the timeout period I am getting this effect more and more often. But I do not see the problem in the code, so guessing...

**Comment by alexs20** [comment] 2016-06-16 02:46
You are welcome, just stuck on "RedissonKeys.flushall()", but on the same get(...)

Unsafe.park(boolean, long) line: not available [native method] [local variables unavailable]	
LockSupport.parkNanos(Object, long) line: 215	
CountDownLatch$Sync(AbstractQueuedSynchronizer).doAcquireSharedNanos(int, long) line: 1037	
CountDownLatch$Sync(AbstractQueuedSynchronizer).tryAcquireSharedNanos(int, long) line: 1328	
CountDownLatch.await(long, TimeUnit) line: 277	
CommandSyncService(CommandAsyncService).get(Future<V>) line: 95	
RedissonKeys.flushall() line: 280	
RedissonLockHeavyTest(BaseTest).before() line: 39

**Comment by kajelas** [comment] 2016-06-16 07:14
@alexs20 
Have you tried to use `RLock.tryLock(long waitTime, long leaseTime, TimeUnit unit)`? It can also set a timeout in this situation.

**Comment by mrniko** [comment] 2016-06-16 08:22
@alexs20 do you use Redisson default settings?

**Comment by mrniko** [comment] 2016-06-16 10:08
@alexs20 try to set subscriptionsPerConnection = 1. Maybe this helps

**Comment by mrniko** [comment] 2016-06-16 10:10
Tried to simulate network delays with 10ms (+/-) 5ms and still can't reproduce this issue. I have used 50 threads

**Comment by alexs20** [comment] 2016-06-16 11:58
@mrniko
In test Number thread in test = 100
In client settings: connection pool = 100, retry = 10
@kajelas
I am using not only RLock, but RBucket and RSemaphore, so the only way to protect from deadlock is to stay on await in get(...) with timeout.

**Comment by mrniko** [comment] 2016-06-16 15:59
I have reproduced it! Looking a solution

**Comment by mrniko** [comment] 2016-06-16 16:35
It's not a real dead lock but problem with CommandDecoder

**Comment by mrniko** [comment] 2016-06-19 11:41
Fixed. Please give it a try

**Comment by alexs20** [comment] 2016-06-20 19:05
Sorry, but it doesnt work.
It stuck with 2 threads test.

Unsafe.park(boolean, long) line: not available [native method]	
LockSupport.park(Object) line: not available	
CountDownLatch$Sync(AbstractQueuedSynchronizer).parkAndCheckInterrupt() line: not available	
CountDownLatch$Sync(AbstractQueuedSynchronizer).doAcquireSharedInterruptibly(int) line: not available	
CountDownLatch$Sync(AbstractQueuedSynchronizer).acquireSharedInterruptibly(int) line: not available	
CountDownLatch.await() line: not available	
CommandSyncService(CommandAsyncService).get(Future<V>) line: 95	
RedissonLock(RedissonObject).get(Future<V>) line: 55	
RedissonLock.lockInterruptibly(long, TimeUnit) line: 121	
RedissonLock.lockInterruptibly() line: 108	
RedissonLock.lock() line: 90	
...

**Comment by mrniko** [comment] 2016-06-20 19:13
with same test?

**Comment by mrniko** [comment] 2016-06-20 19:15
@kajelas does it help you?

**Comment by mrniko** [comment] 2016-06-20 19:17
@alexs20 Could you turn on the logging?

**Comment by alexs20** [comment] 2016-06-20 20:47
Now it stuck in single thread, but stack-trace is the same.
Attaching log file. Sorry but I can not provide the test example. it contains internal business logic..

[logFile.2016-06-20.log.zip](https://github.com/mrniko/redisson/files/324310/logFile.2016-06-20.log.zip)

**Comment by mrniko** [comment] 2016-06-21 09:27
Still can't reproduce it, but I made some change. Could you try it?

**Comment by alexs20** [comment] 2016-06-21 18:26
Now it looks better. Till now all test working fine. But I had to increase timeout period to 3000. With default 1000 some test failed because of response timeout.

**Comment by mrniko** [comment] 2016-06-21 20:28
> With default 1000 some test failed because of response timeout.

I suggest you to play with GC params to solve it

**Closed** 2016-06-24 10:35 UTC

**Comment by mrniko** [comment] 2016-07-04 11:47
@alexs20 Hi!

Could you please try version from [new_pubsub](https://github.com/mrniko/redisson/tree/new_pubsub) branch with your tests?
